fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        obtao_blog:
            client: default
            types:
                oferta:
                    mappings:
                        id:
                            type: integer
                        fechaInicio :
                            type : date
                        fechaFin :
                            type : date
                        nombre:
                            type: text
                        descripcion:
                            type: text
                        published :
                            type : boolean
                        title : ~
                        content : ~
                    persistence:
                        driver: orm
                        model: Obtao\BlogBundle\Entity\Article
                        finder: ~
                        provider: ~
                        listener: ~
